CREATE TABLE Registration (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    userId BIGINT(20) NOT NULL,
    courseId BIGINT(20) NOT NULL,
    registrationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_Studant FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
    CONSTRAINT fk_Course FOREIGN KEY (courseId) REFERENCES Course(id) ON DELETE CASCADE,
    CONSTRAINT unique_user_course UNIQUE (userId, courseId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;